[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
ffi = true
evm_version = "shanghai"
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
wrap_comments = true
